### PR TITLE
Set z-index to 1 on header to fix styling bug

### PR DESCRIPTION
**Pull request by imam**
### Description
Sometimes fields are hovering over the header

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Interesting. Thank you @imam for the pull request. Could you please sign our Contributor's License Agreement? https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by imam** [comment]
@bajtos done

**Comment by rmg** [comment]
@imam did you complete the form at https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer after signing in? I see your account, but no signatures attached to it.

**Comment by imam** [comment]
@rmg I'm sorry I just realize I haven't. Now it's should be completed

**Comment by bajtos** [comment]
@imam while I am not able to reproduce the issue you are facing, I guess that explicitly setting `z-index` should not cause any harm and we can land this change.

**Comment by bajtos** [comment]
Landed 🎉 

Thank you for the contribution!

**Pull request merged**
