### PR TITLE
Added another example for explorer Advanced Usage

### PR DESCRIPTION
**Pull request by pratheekhegde**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
Thanks for the contribution! :shipit:

**Comment by superkhau** [comment]
tset please
@slnode test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@PradnyaBaviskar This PR needed rebasing with master. Helped you land it at https://github.com/strongloop/loopback-component-explorer/pull/192. Thanks again for the contribution! :shipit:

**Comment by superkhau** [comment]
Closing in favour of #192

**Pull request closed without merging**
