### PR TITLE
adding on started listener to display nestRemoting method in swagger …

### PR DESCRIPTION
**Pull request by DAVIDFlavien**
### Description

Add _nestRemoting_ routes in the explorer

#### Related issues

- #167 
- strongloop/loopback#2409

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by DAVIDFlavien** [comment]
updated in #d0f70cc71f2412f0d32af87f6944e82e6d18a413
See associated PR on strongloop/loopback#3322

**Comment by bajtos** [comment]
Closing as abandoned.

**Comment by bajtos** [comment]
@DAVIDFlavien I am puzzled by your "thumbs down" on my https://github.com/strongloop/loopback-component-explorer/pull/208#issuecomment-296700391. If you are still keen to get this finished, then please address my comments above and either reopen this pull request or send a new one.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
Close as I'm reworking on the PR at https://github.com/strongloop/loopback-component-explorer/pull/222

**Pull request closed without merging**
