### PR TITLE
WIP(swagger-ui): Upgrade to v3

### PR DESCRIPTION
**Pull request by STRML**
This is a work in progress; please don't merge yet.

V3 brings with it [some major changes](https://github.com/swagger-api/swagger-ui/releases/tag/v3.0.0). Most of the changes are great.

Issues blocking release in loopback-component-explorer:

- [ ] Restyle header for LoopBack
- [x] [Shebang/routing support](https://github.com/swagger-api/swagger-ui/issues/2884) - fixed by https://github.com/swagger-api/swagger-ui/issues/2884
- [ ] loopback-swagger need to produce auth metadata - see https://github.com/strongloop/loopback-swagger/issues/65

The npm package no longer exports a bundle. I'm not sure if this is intentional. For this reason, I've added a dev-only script to copy from github releases.

### CODE REVIEW

**Comment by bajtos** [comment]
Great stuff, @STRML! Let us know when the pull request is ready for review.

**Comment by STRML** [comment]
Will do. We'll want to wait a few weeks for Swagger-UI v3 to stabilize. Minor releases are still shipping some pretty fundamental bugfixes. But after that, it should be quite nice.

**Comment by shockey** [comment]
Hi everyone! Jumping in from Swagger-land to share some good news....

> The npm package no longer exports a bundle. I'm not sure if this is intentional. For this reason, I've added a dev-only script to copy from github releases.

In 3.0.7 we started maintaining a [`swagger-ui-dist`](https://www.npmjs.com/package/swagger-ui-dist) package that exports our entire dist folder, in the style of 2.x 😄

**Comment by bajtos** [comment]
@STRML ping, what's the status of this pull request? Has Swagger-UI v3 stabilized yet?

**Comment by bajtos** [comment]
Hey @STRML, what's the status of this pull request? Are you still keen to get it finished? Should we close it as abandoned?

**Comment by STRML** [comment]
Hey - I definitely want to get this through, had really just gotten busy and forgotten about it, and the earlier `dist` issue required a hack I really didn't want to get merged.

Now that it's resolved I'm going to take another look today and push up something mergeable.

**Comment by STRML** [comment]
Ok, the latest push gets us to a working setup, and we're much more in-line with base Swagger-UI (fewer customizations). 

Swagger-UI 3 has a lot more customizability than previous versions, so I've added the ability to write options to `window.swaggerUIOptions`. These options will take priority over the defaults.

screen shot 2017-09-11 at 7 51 31 am
screen shot 2017-09-11 at 7 51 37 am

Syntax highlighting is partially in ([microlight](https://github.com/asvd/microlight) is running) but it's very limited (https://github.com/swagger-api/swagger-ui/issues/3189). Additionally, `highlightSizeThreshold` is [still not in](https://github.com/swagger-api/swagger-ui/issues/3105).

Authorization is an issue.

We're going to require https://github.com/strongloop/loopback-swagger/issues/65 be fixed (`securityDefinitions`) in order for the native "Authorize" popup to show:

screen shot 2017-09-11 at 7 58 33 am
screen shot 2017-09-11 at 7 58 37 am

**Comment by bajtos** [comment]
@STRML thank you for the update, looks like there is quite a lot of work needed to make this happen. From custom style to authorization support. Do you have bandwidth to implement these changes?

**Comment by STRML** [comment]
Not particularly, across all projects. If you guys can find some help to do the rest of the work on loopback-swagger such that we have all the fields we need, I can finish the rest here.

**Comment by sebastianhaas** [comment]
I might also be able to help out, if there are some marked-off tasks that are good for contribution.

**Comment by bajtos** [comment]
@sebastianhaas thank you for the offer. Could you perhaps take a look at https://github.com/strongloop/loopback-swagger/issues/65? I think that's the biggest blocker right now.

**Comment by sebastianhaas** [comment]
Your stale bot is very annoying.

**Comment by fraxken** [comment]
Any news about this upgrade ? Thanks for your awesome work !

**Comment by STRML** [comment]
https://github.com/strongloop/loopback-swagger/issues/65 is a blocker.

**Comment by STRML** [comment]
Just a status report: nothing has really changed since https://github.com/strongloop/loopback-component-explorer/pull/209#issuecomment-328522783 - swagger-ui still has the missing syntax highlight features and threshold, and we still need to properly export authSchema to move forward with authorization (which would be a pretty major regression blocking release).

**Comment by bajtos** [comment]
Thank you for the update, @STRML.

The main focus of the IBM team is on LoopBack 4 now, we don't have bandwidth to help with upgrading swagger-ui to v3 and/or improving loopback-swagger to correctly export authSchema. We are relying on the community to drive the progress here.

**Comment by bajtos** [comment]
> The npm package no longer exports a bundle. I'm not sure if this is intentional. For this reason, I've added a dev-only script to copy from github releases.

FWIW, we are successfully using https://www.npmjs.com/package/swagger-ui-dist in the upcoming 4.0 version of LoopBack.

**Pull request closed without merging**
