### PR TITLE
Update lodash

### PR DESCRIPTION
**Pull request by shimks**
### Description
Fixes https://nodesecurity.io/advisories/577

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by shimks** [comment]
@bajtos I know we don't plan on maintaining `2.x` for this repo, but the alternative to fixing this vulnerability (https://nodesecurity.io/advisories/577) was to update the version of `loopback-component-workspace` given as template in `loopback-workspace` to the latest one. It seems like the major difference between the current one and the latest (2.x vs 6.x) seems to be the fact that we use our own fork (?) of `swagger-ui`. Do you know how big the difference is between the mainline swagger-ui and our deprecated one?

@virkt25 has also mentioned that the vulnerability is most likely not reachable through us so the fix may not even be needed

**Comment by virkt25** [comment]
Oops. Let me clarify - I have not looked to see if this particular vulnerability can be reached from our code (it likely can if `lodash`'s deepMerge is being used with data coming from the consumer).

I just meant to give an example that there are times a vulnerability isn't applicable to us because there is no path in code that leads to it.

**Comment by shimks** [comment]
lodash is only used for `defaults` in this package, so I was able to confirm that the vulnerability is not reachable through this package.

**Comment by virkt25** [comment]
Awesome @shimks

**Comment by bajtos** [comment]
I did a quick search in loopback-workspace to find all occurrences of loopback-component-explorer ([query](https://github.com/strongloop/loopback-workspace/blob/f3fc7f12db9501a5cd8d6d24d0979f3ce8cea90c/package.json#L31)).

https://github.com/strongloop/loopback-workspace/blob/f3fc7f12db9501a5cd8d6d24d0979f3ce8cea90c/package.json#L31

The top-level package.json uses explorer 2.x. I believe this explorer is purely a helper tool for people writing web clients (e.g. StrongLoop Arc) against workspace REST API, we can safely upgrade it to a newer explorer version. Just check which Node.js versions are supported by workspace and by explorer.

https://github.com/strongloop/loopback-workspace/blob/b2875319b7666b050ba03b24e2b8031ad3e40060/common/models/workspace.js#L42-L46

Projects scaffolded with LB 2.x are installing 2.x version of the explorer. You are right about the difference between swagger-ui features provided by explorer 2.x vs. 3+ (they are large!). On the other hand, this template is used only when creating a new project. I have always felt that it's ok to change configuration of new projects in backwards-incompatible way without having to bump up loopback-workspace semver-major version, because how often do you compare the result of `lb app` across different version of `lb` command?

I am proposing to update the LB 2.x template to use the latest LTS version of explorer, which is 5.x.

**Comment by shimks** [comment]
Good to hear that there shouldn't be too much issue with upgrading explorer. I'll close this PR once strongloop/loopback-workspace#517 lands

**Pull request closed without merging**
