### PR TITLE
examples launch fix

### PR DESCRIPTION
**Pull request by Coobaha**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@Coobaha Can you fix the conflicts? Let's get this merged in.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by Coobaha** [comment]
@superkhau fixed, there was code-style conflict :) :shipit:

**Comment by superkhau** [comment]
LGTM. Thanks for the contribution! ;)

**Pull request merged**
