### PR TITLE
CSS line terminations

### PR DESCRIPTION
**Pull request by bigwisu**
a few line termination fixes in CSS

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Thanks for the contribution! :+1: Can you sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer

**Comment by bigwisu** [comment]
cool... CLA signed :)

**Comment by superkhau** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Thanks for the contribution! :shipit:

**Comment by superkhau** [comment]
@bajtos Do we need to backport this it 2.x and 3.x now?

**Comment by bajtos** [comment]
Let's backport to 3.x only and wait if there is anybody asking for this fix in 2.x versions too.

**Pull request merged**
