### PR TITLE
[SEMVER-MAJOR] Update to mainline swagger-ui 

### PR DESCRIPTION
**Pull request by STRML**
Reverts #107.

Fixes: 

* https://github.com/strongloop/strong-swagger-js/pull/11
* https://github.com/strongloop/strong-swagger-ui/pull/13
* Many [open Issues](https://github.com/strongloop/loopback-component-explorer/issues)

### CODE REVIEW

**Comment by STRML** [comment]
@shelbys Are you still using loopback-component-explorer? Unfortunately your old commits were all CS (which has been removed from swagger-ui) so we'd need to rebase strong-swagger-ui into JS before attempting to merge any of [your commits](https://github.com/swagger-api/swagger-ui/compare/master...strongloop:master).

**Comment by shelbys** [comment]
@STRML - We're still using `shelbys/loopback-explorer` which in-turn uses `shelbys/swagger-ui`.  Last I knew, @bajtos was working on porting equivalent changes for everything we care about

**Comment by bajtos** [comment]
Yes, the idea was to quickly port @shelbys' changes to our fork, while keeping our fork up-to-date with the upstream repository. Clearly, that plan did not play out well.

I am fine with reverting loopback-explorer back to use `swagger-ui` directly.

I am concerned this will be a breaking change though, as it's dropping changes made in strong-swagger-ui. Is it an issue?

**Comment by STRML** [comment]
@bajtos I haven't seen any issues. Our explorer is live at https://testnet.bitmex.com/api/explorer/.

**Comment by bajtos** [comment]
@STRML I have fixed the commit message to follow the [50/72](http://loopback.io/doc/en/contrib/git-commit-messages.html) rule and force-pushed back into your branch. Preparing a new major release requires a bit more work, I'll try to get it done soon, so that we can land your patch.

**Comment by bajtos** [comment]
See also https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by STRML** [comment]
Okay, sure? Plenty of other commits in this repo that violate that but I don't mind you changing hte message.

**Comment by bajtos** [comment]
Landed and released as 3.0.0.

Thank you @STRML for raising up this issue and contributing the fix.

FYI: We treat 3.0 releases as "Release Candidate" versions now, to gather feedback and fix any issues before making a GA release. Therefore 3.x.y releases are published under the tag `next` to npmjs.org. `npm install loopback-component-explorer` will fetch 2.x version, users have to explicitly request `^3.0.0` if they like to use the upcoming version.

**Pull request merged**
