### PR TITLE
Use "cursor: pointer" for the "Add token" button

### PR DESCRIPTION
**Pull request by sirajalam049**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-component-explorer) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by sirajalam049** [comment]
.ok\W+to\W+test.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Landed, thank you @sirajalam049 for the contribution ❤️

**Pull request merged**
