### PR TITLE
Update lodash version

### PR DESCRIPTION
**Pull request by adrian999999**
refer to ticket #241

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
Thanks for the PR @adrian999999 

Can you please sign the CLA by clicking on the `Details` for the `clahub` check.

**Comment by adrian999999** [comment]
@virkt25 I signed the CLA by somehow it does not work.

**Comment by virkt25** [comment]
@rmg Any ideas what's going on with the clahub?

**Comment by bajtos** [comment]
Sorry, the 2.x version is no longer supported, see [here](https://github.com/strongloop/loopback-component-explorer/blob/master/README.md#supported-versions). Please upgrade to a newer version of loopback-component-explorer.

**Pull request closed without merging**
